module.exports = 
[
    {model_name: "editor/entities/jc_characters/civilians/01_generic/female/civ_female_gen_001.ee", name: "Female Civilian 1"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/female/civ_female_gen_002.ee", name: "Female Civilian 2"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/female/civ_female_gen_003.ee", name: "Female Civilian 3"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/female/civ_female_gen_004.ee", name: "Female Civilian 4"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/female/civ_female_gen_005.ee", name: "Female Civilian 5"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/female/civ_female_gen_006.ee", name: "Female Civilian 6"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/female/civ_female_gen_007.ee", name: "Female Civilian 7"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/female/civ_female_gen_008.ee", name: "Female Civilian 8"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/female/civ_female_gen_009.ee", name: "Female Civilian 9"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/female/civ_female_gen_010.ee", name: "Female Civilian 10"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/female/civ_female_gen_011.ee", name: "Female Civilian 11"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/female/civ_female_gen_012.ee", name: "Female Civilian 12"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/female/civ_female_gen_013.ee", name: "Female Civilian 13"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/female/civ_female_gen_014.ee", name: "Female Civilian 14"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/female/civ_female_gen_015.ee", name: "Female Civilian 15"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/female/civ_female_gen_016.ee", name: "Female Civilian 16"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/male/civ_male_gen_001_avg.ee", name: "Male Civilian 1"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/male/civ_male_gen_002_avg.ee", name: "Male Civilian 2"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/male/civ_male_gen_003_avg.ee", name: "Male Civilian 3"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/male/civ_male_gen_004_avg.ee", name: "Male Civilian 4"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/male/civ_male_gen_005_avg.ee", name: "Male Civilian 5"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/male/civ_male_gen_006_avg.ee", name: "Male Civilian 6"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/male/civ_male_gen_007_avg.ee", name: "Male Civilian 7"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/male/civ_male_gen_008_avg.ee", name: "Male Civilian 8"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/male/civ_male_gen_009_avg.ee", name: "Male Civilian 9"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/male/civ_male_gen_010_avg.ee", name: "Male Civilian 10"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/male/civ_male_gen_011_avg.ee", name: "Male Civilian 11"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/male/civ_male_gen_012_avg.ee", name: "Male Civilian 12"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/male/civ_male_gen_013_avg.ee", name: "Male Civilian 13"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/male/civ_male_gen_014_avg.ee", name: "Male Civilian 14"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/male/civ_male_gen_015_avg.ee", name: "Male Civilian 15"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/male/civ_male_gen_016_avg.ee", name: "Male Civilian 16"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/male/civ_male_gen_017_avg.ee", name: "Male Civilian 17"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/male/civ_male_gen_018_avg.ee", name: "Male Civilian 18"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/male/civ_male_gen_019_avg.ee", name: "Male Civilian 19"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/male/civ_male_greenman.ee", name: "GREENMAN"},
    {model_name: "editor/entities/jc_characters/civilians/01_generic/male/civ_male_pinata_omar.ee", name: "Pinata Omar"},
    {model_name: "editor/entities/jc_characters/civilians/02_clergy/nun_01.ee", name: "Nun 1"},
    {model_name: "editor/entities/jc_characters/civilians/02_clergy/nun_02.ee", name: "Nun 2"},
    {model_name: "editor/entities/jc_characters/civilians/02_clergy/nun_03.ee", name: "Nun 3"},
    {model_name: "editor/entities/jc_characters/civilians/02_clergy/nun_clear_heat.ee", name: "Nun Clear Heat"}, // Maybe disable this
    {model_name: "editor/entities/jc_characters/civilians/02_clergy/priest_01.ee", name: "Priest 1"},
    {model_name: "editor/entities/jc_characters/civilians/02_clergy/priest_clear_heat.ee", name: "Priest Clear Heat"}, // Maybe disable this
    {model_name: "editor/entities/jc_characters/civilians/03_civil_servant/female_civil_servant_01.ee", name: "Female Servant 1"},
    {model_name: "editor/entities/jc_characters/civilians/03_civil_servant/female_civil_servant_01_propvan_driver.ee", name: "Female Driver 1"},
    {model_name: "editor/entities/jc_characters/civilians/03_civil_servant/male_civil_servant_01.ee", name: "Male Servant 1"},
    {model_name: "editor/entities/jc_characters/civilians/03_civil_servant/male_civil_servant_01_propvan_driver.ee", name: "Male Driver 1"},
    {model_name: "editor/entities/jc_characters/civilians/03_civil_servant/male_civil_servant_02_bus.ee", name: "Male Driver 2"},
    {model_name: "editor/entities/jc_characters/civilians/04_elder/female_elder_001_avg.ee", name: "Female Elder 1"},
    {model_name: "editor/entities/jc_characters/civilians/04_elder/female_elder_002_avg.ee", name: "Female Elder 2"},
    {model_name: "editor/entities/jc_characters/civilians/04_elder/female_elder_003_avg.ee", name: "Female Elder 3"},
    {model_name: "editor/entities/jc_characters/civilians/04_elder/male_elder_001_avg.ee", name: "Male Elder 1"},
    {model_name: "editor/entities/jc_characters/civilians/04_elder/male_elder_002_heavy.ee", name: "Male Elder 2 (Heavy)"},
    {model_name: "editor/entities/jc_characters/civilians/04_elder/male_elder_003_avg.ee", name: "Male Elder 3"},
    {model_name: "editor/entities/jc_characters/civilians/04_elder/male_elder_004_avg.ee", name: "Male Elder 4"},
    {model_name: "editor/entities/jc_characters/civilians/04_elder/male_elder_005_avg.ee", name: "Male Elder 5"},
    {model_name: "editor/entities/jc_characters/civilians/04_elder/male_elder_006_avg.ee", name: "Male Elder 6"},
    {model_name: "editor/entities/jc_characters/civilians/04_elder/male_elder_007_heavy.ee", name: "Male Elder 7 (Heavy)"},
    {model_name: "editor/entities/jc_characters/civilians/04_elder/male_elder_008_avg.ee", name: "Male Elder 8"},
    {model_name: "editor/entities/jc_characters/civilians/04_elder/male_elder_009_avg.ee", name: "Male Elder 9"},
    {model_name: "editor/entities/jc_characters/civilians/05_farmer/female_farmer_002.ee", name: "Female Farmer 2"},
    {model_name: "editor/entities/jc_characters/civilians/05_farmer/female_farmer_003.ee", name: "Female Farmer 3"},
    {model_name: "editor/entities/jc_characters/civilians/05_farmer/female_farmer_003_banana_stand.ee", name: "Female Banana Farmer"},
    {model_name: "editor/entities/jc_characters/civilians/05_farmer/female_farmer_old_001.ee", name: "Old Female Farmer 1"},
    {model_name: "editor/entities/jc_characters/civilians/05_farmer/male_farmer_002_avg.ee", name: "Male Farmer 2"},
    {model_name: "editor/entities/jc_characters/civilians/05_farmer/male_farmer_003_avg.ee", name: "Male Farmer 3"},
    {model_name: "editor/entities/jc_characters/civilians/05_farmer/male_farmer_004_avg.ee", name: "Male Farmer 4"},
    {model_name: "editor/entities/jc_characters/civilians/05_farmer/male_farmer_005_avg.ee", name: "Male Farmer 5"},
    {model_name: "editor/entities/jc_characters/civilians/05_farmer/male_farmer_006_avg.ee", name: "Male Farmer 6"},
    {model_name: "editor/entities/jc_characters/civilians/05_farmer/male_farmer_007_avg.ee", name: "Male Farmer 7"},
    {model_name: "editor/entities/jc_characters/civilians/05_farmer/male_farmer_008_avg.ee", name: "Male Farmer 8"},
    {model_name: "editor/entities/jc_characters/civilians/05_farmer/male_farmer_009_avg.ee", name: "Male Farmer 9"},
    {model_name: "editor/entities/jc_characters/civilians/05_farmer/male_farmer_old_001_heavy.ee", name: "Old Male Farmer 1 (Heavy)"},
    {model_name: "editor/entities/jc_characters/civilians/06_vagrant/vagrant_female_gen_001_avg.ee", name: "Female Vagrant 1"},
    {model_name: "editor/entities/jc_characters/civilians/06_vagrant/vagrant_female_gen_002_avg.ee", name: "Female Vagrant 2"},
    {model_name: "editor/entities/jc_characters/civilians/06_vagrant/vagrant_female_gen_003_avg.ee", name: "Female Vagrant 3"},
    {model_name: "editor/entities/jc_characters/civilians/06_vagrant/vagrant_male_gen_001_avg.ee", name: "Male Vagrant 1"},
    {model_name: "editor/entities/jc_characters/civilians/06_vagrant/vagrant_male_gen_002_avg.ee", name: "Male Vagrant 2"},
    {model_name: "editor/entities/jc_characters/civilians/06_vagrant/vagrant_male_gen_003_avg.ee", name: "Male Vagrant 3"},
    {model_name: "editor/entities/jc_characters/civilians/07_tourist/civ_female_tourist_001_avg.ee", name: "Female Tourist 1"},
    {model_name: "editor/entities/jc_characters/civilians/07_tourist/civ_female_tourist_002_avg.ee", name: "Female Tourist 2"},
    {model_name: "editor/entities/jc_characters/civilians/07_tourist/civ_female_tourist_003_avg.ee", name: "Female Tourist 3"},
    {model_name: "editor/entities/jc_characters/civilians/07_tourist/civ_female_tourist_004_avg.ee", name: "Female Tourist 4"},
    {model_name: "editor/entities/jc_characters/civilians/07_tourist/civ_male_tourist_001_avg.ee", name: "Male Tourist 1"},
    {model_name: "editor/entities/jc_characters/civilians/07_tourist/civ_male_tourist_002_avg.ee", name: "Male Tourist 2"},
    {model_name: "editor/entities/jc_characters/civilians/07_tourist/civ_male_tourist_003_avg.ee", name: "Male Tourist 3"},
    {model_name: "editor/entities/jc_characters/civilians/07_tourist/civ_male_tourist_004_avg.ee", name: "Male Tourist 4"},
    {model_name: "editor/entities/jc_characters/civilians/08_beach/civ_female_beach_001.ee", name: "Female Beach 1"},
    {model_name: "editor/entities/jc_characters/civilians/08_beach/civ_female_beach_002.ee", name: "Female Beach 2"},
    {model_name: "editor/entities/jc_characters/civilians/08_beach/civ_female_beach_003.ee", name: "Female Beach 3"},
    {model_name: "editor/entities/jc_characters/civilians/08_beach/civ_female_beach_004.ee", name: "Female Beach 4"},
    {model_name: "editor/entities/jc_characters/civilians/08_beach/civ_female_beach_005.ee", name: "Female Beach 5"},
    {model_name: "editor/entities/jc_characters/civilians/08_beach/civ_female_beach_006.ee", name: "Female Beach 6"},
    {model_name: "editor/entities/jc_characters/civilians/08_beach/civ_female_beach_007.ee", name: "Female Beach 7"},
    {model_name: "editor/entities/jc_characters/civilians/08_beach/civ_female_beach_008.ee", name: "Female Beach 8"},
    {model_name: "editor/entities/jc_characters/civilians/08_beach/civ_male_beach_001.ee", name: "Male Beach 1"},
    {model_name: "editor/entities/jc_characters/civilians/08_beach/civ_male_beach_002.ee", name: "Male Beach 2"},
    {model_name: "editor/entities/jc_characters/civilians/08_beach/civ_male_beach_003.ee", name: "Male Beach 3"},
    {model_name: "editor/entities/jc_characters/civilians/08_beach/civ_male_beach_004.ee", name: "Male Beach 4"},
    {model_name: "editor/entities/jc_characters/civilians/08_beach/civ_male_beach_005.ee", name: "Male Beach 5"},
    {model_name: "editor/entities/jc_characters/civilians/08_beach/civ_male_beach_006.ee", name: "Male Beach 6"},
    {model_name: "editor/entities/jc_characters/civilians/09_construction_workers/male_construction_worker_01.ee", name: "Construction Worker 1"},
    {model_name: "editor/entities/jc_characters/civilians/09_construction_workers/male_construction_worker_02.ee", name: "Construction Worker 2"},
    {model_name: "editor/entities/jc_characters/civilians/09_construction_workers/male_construction_worker_03.ee", name: "Construction Worker 3"},
    {model_name: "editor/entities/jc_characters/civilians/09_construction_workers/male_construction_worker_04.ee", name: "Construction Worker 4"},
    {model_name: "editor/entities/jc_characters/civilians/09_construction_workers/male_dock_worker_01.ee", name: "Dock Worker 1"},
    {model_name: "editor/entities/jc_characters/civilians/09_construction_workers/male_dock_worker_02.ee", name: "Dock Worker 2"},
    {model_name: "editor/entities/jc_characters/civilians/10_business/civ_female_business_001.ee", name: "Female Business 1"},
    {model_name: "editor/entities/jc_characters/civilians/10_business/civ_female_business_002.ee", name: "Female Business 2"},
    {model_name: "editor/entities/jc_characters/civilians/10_business/civ_female_business_003.ee", name: "Female Business 3"},
    {model_name: "editor/entities/jc_characters/civilians/10_business/civ_female_business_004.ee", name: "Female Business 4"},
    {model_name: "editor/entities/jc_characters/civilians/10_business/civ_female_business_005.ee", name: "Female Business 5"},
    {model_name: "editor/entities/jc_characters/civilians/10_business/civ_female_business_006.ee", name: "Female Business 6"},
    {model_name: "editor/entities/jc_characters/civilians/10_business/civ_female_business_007.ee", name: "Female Business 7"},
    {model_name: "editor/entities/jc_characters/civilians/10_business/civ_female_business_008.ee", name: "Female Business 8"},
    {model_name: "editor/entities/jc_characters/civilians/10_business/civ_male_business_001_avg.ee", name: "Male Business 1"},
    {model_name: "editor/entities/jc_characters/civilians/10_business/civ_male_business_002_avg.ee", name: "Male Business 2"},
    {model_name: "editor/entities/jc_characters/civilians/10_business/civ_male_business_003_avg.ee", name: "Male Business 3"},
    {model_name: "editor/entities/jc_characters/civilians/10_business/civ_male_business_004_avg.ee", name: "Male Business 4"},
    {model_name: "editor/entities/jc_characters/civilians/10_business/civ_male_business_005_avg.ee", name: "Male Business 5"},
    {model_name: "editor/entities/jc_characters/civilians/10_business/civ_male_business_006_avg.ee", name: "Male Business 6"},
    {model_name: "editor/entities/jc_characters/civilians/10_business/civ_male_business_007_avg.ee", name: "Male Business 7"},
    {model_name: "editor/entities/jc_characters/civilians/10_business/civ_male_business_008_avg.ee", name: "Male Business 8"},
    {model_name: "editor/entities/jc_characters/civilians/11_scientists/civ_female_scientist_001.ee", name: "Female Scientist"},
    {model_name: "editor/entities/jc_characters/civilians/11_scientists/civ_male_scientist_001.ee", name: "Male Scientist 1"},
    {model_name: "editor/entities/jc_characters/civilians/11_scientists/civ_male_scientist_002.ee", name: "Male Scientist 2"},
    {model_name: "editor/entities/jc_characters/civilians/11_scientists/civ_male_scientist_003.ee", name: "Male Scientist 3"},
    {model_name: "editor/entities/jc_characters/civilians/civilian_proto.ee", name: "Civilian Prototype"}, // Maybe disable this
    {model_name: "editor/entities/jc_characters/civilians/prototype/civilian_face_anim_test.ee", name: "Civilian Anim Test"}, // Maybe disable this
    {model_name: "editor/entities/jc_characters/enemies/02_army/armored_driver/armored_driver.ee", name: "Armored Driver"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/assault_trooper/assault_trooper.ee", name: "Assault Trooper"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/biker_scout/biker_scout01.ee", name: "Biker Scout"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/black_hand_ghost/black_hand_ghost.ee", name: "Black Hand Ghost"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/black_hand_grunt/black_hand_grunt.ee", name: "Black Hand Grunt"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/black_hand_titan/black_hand_titan.ee", name: "Black Hand Titan"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/commander/commander.ee", name: "Commander"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/debug/gen_soldier_debug_ar.ee", name: "Soldier Debug"}, // Maybe disable this
    {model_name: "editor/entities/jc_characters/enemies/02_army/demolition/demo_soldier.ee", name: "Demolition Soldier 1"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/demolition/demo_soldier_02.ee", name: "Demolition Soldier 2"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/gen_soldier/gen_soldier.ee", name: "Soldier 1"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/gen_soldier/gen_soldier02.ee", name: "Soldier 2"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/gen_soldier/gen_soldier03.ee", name: "Soldier 3"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/gen_soldier/gen_soldier04.ee", name: "Soldier 4"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/gen_soldier/gen_soldier05.ee", name: "Soldier 5"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/gen_soldier_car/gen_soldier_car.ee", name: "Soldier Car"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/machinegunner/machinegunner.ee", name: "Machinegunner 1"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/machinegunner/machinegunner02.ee", name: "Machinegunner 2"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/machinegunner/machinegunner03.ee", name: "Machinegunner 3"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/paratrooper/spawned_paratrooper.ee", name: "Paratrooper"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/pilot/pilot.ee", name: "Pilot"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/pilot/pilot_jet.ee", name: "Jet Pilot"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/ravello_guard/ravello_guard.ee", name: "DiRavello Guard"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/shock_trooper/shock_trooper.ee", name: "Shock Trooper 1"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/shock_trooper/shock_trooper02.ee", name: "Shock Trooper 2"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/sniper/sniper.ee", name: "Sniper"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/soldier_elite/soldier_elite.ee", name: "Elite Soldier 1"},
    {model_name: "editor/entities/jc_characters/enemies/02_army/soldier_elite/soldier_elite02.ee", name: "Elite Soldier 2"},
    {model_name: "editor/entities/jc_characters/enemies/03_mafia/mafia001.ee", name: "Mafia 1"},
    {model_name: "editor/entities/jc_characters/enemies/03_mafia/mafia002.ee", name: "Mafia 2"},
    {model_name: "editor/entities/jc_characters/enemies/04_police/police_captain/police_captain.ee", name: "Police Captain"},
    {model_name: "editor/entities/jc_characters/enemies/04_police/police_officer/police_officer.ee", name: "Police Officer"},
    {model_name: "editor/entities/jc_characters/enemies/04_police/police_swat/police_swat.ee", name: "Police SWAT"},
    {model_name: "editor/entities/jc_characters/enemies/05_drm/drm_captain/drm_captain.ee", name: "DRM Captain"},
    {model_name: "editor/entities/jc_characters/enemies/05_drm/drm_grunt/drm_grunt.ee", name: "DRM Grunt"},
    {model_name: "editor/entities/jc_characters/enemies/05_drm/drm_swat/drm_swat.ee", name: "DRM SWAT"},
    {model_name: "editor/entities/jc_characters/main_characters/annika/annika.ee", name: "Annika"},
    {model_name: "editor/entities/jc_characters/main_characters/bolo/bolo.ee", name: "Bolo"},
    {model_name: "editor/entities/jc_characters/main_characters/dimah/dimah.ee", name: "Dimah"},
    {model_name: "editor/entities/jc_characters/main_characters/di_ravello/di_ravello.ee", name: "DiRavello"},
    {model_name: "editor/entities/jc_characters/main_characters/luciano/luciano.ee", name: "Luciano"},
    {model_name: "editor/entities/jc_characters/main_characters/mario/mario.ee", name: "Mario"},
    {model_name: "editor/entities/jc_characters/main_characters/pierce/pierce.ee", name: "Pierce"},
    {model_name: "editor/entities/jc_characters/main_characters/rosa/rosa.ee", name: "Rosa"},
    {model_name: "editor/entities/jc_characters/main_characters/sheldon/sheldon.ee", name: "Sheldon"},
    {model_name: "editor/entities/jc_characters/main_characters/teo/teo.ee", name: "Teo"},
    {model_name: "editor/entities/jc_characters/main_characters/zeno/zeno.ee", name: "Zeno"},
    {model_name: "editor/entities/jc_characters/previewer/civilian_previewer.ee", name: "Civilian Previewer"}, // Maybe disable this
    {model_name: "editor/entities/jc_characters/previewer/enemy_previewer.ee", name: "Enemy Previewer"}, // Maybe disable this
    {model_name: "editor/entities/jc_characters/previewer/rico_preview.ee", name: "Rico Preview"}, // Maybe disable this
    {model_name: "editor/entities/jc_characters/prisoner/male_prisoner_001_avg.ee", name: "Male Prisoner 1"},
    {model_name: "editor/entities/jc_characters/prisoner/male_prisoner_002_avg.ee", name: "Male Prisoner 2"},
    {model_name: "editor/entities/jc_characters/prisoner/male_prisoner_003_avg.ee", name: "Male Prisoner 3"},
    {model_name: "editor/entities/jc_characters/prisoner/male_prisoner_004_avg.ee", name: "Male Prisoner 4"},
    {model_name: "editor/entities/jc_characters/prisoner/male_prisoner_005_avg.ee", name: "Male Prisoner 5"},
    {model_name: "editor/entities/jc_characters/prisoner/prisoner_civilians/male_prisoner_civilian_001_avg.ee", name: "Male Prisoner 6"},
    {model_name: "editor/entities/jc_characters/prisoner/prisoner_civilians/male_prisoner_civilian_002_avg.ee", name: "Male Prisoner 7"},
    {model_name: "editor/entities/jc_characters/prisoner/prisoner_civilians/male_prisoner_civilian_003_avg.ee", name: "Male Prisoner 8"},
    {model_name: "editor/entities/jc_characters/prisoner/prisoner_civilians/male_prisoner_civilian_004_avg.ee", name: "Male Prisoner 9"},
    {model_name: "editor/entities/jc_characters/prisoner/prisoner_civilians/male_prisoner_civilian_005_avg.ee", name: "Male Prisoner 10"},
    {model_name: "editor/entities/jc_characters/prototypes/combat_position_tester.ee", name: "Combat Position Tester"}, // Maybe disable this
    {model_name: "editor/entities/jc_characters/prototypes/debug_follower.ee", name: "Debug Follower"}, // Maybe disable this
    {model_name: "editor/entities/jc_characters/prototypes/shock_civ.ee", name: "Civilian Shock"},
    {model_name: "editor/entities/jc_characters/prototypes/sniper_civ.ee", name: "Civilian Sniper"},
    {model_name: "editor/entities/jc_characters/rebels/female_rebel_001_avg.ee", name: "Female Rebel 1"},
    {model_name: "editor/entities/jc_characters/rebels/female_rebel_002_avg.ee", name: "Female Rebel 2"},
    {model_name: "editor/entities/jc_characters/rebels/female_rebel_003_avg.ee", name: "Female Rebel 3"},
    {model_name: "editor/entities/jc_characters/rebels/female_rebel_004_avg.ee", name: "Female Rebel 4"},
    {model_name: "editor/entities/jc_characters/rebels/female_rebel_005_avg.ee", name: "Female Rebel 5"},
    {model_name: "editor/entities/jc_characters/rebels/female_rebel_006_avg.ee", name: "Female Rebel 6"},
    {model_name: "editor/entities/jc_characters/rebels/female_rebel_007_avg.ee", name: "Female Rebel 7"},
    {model_name: "editor/entities/jc_characters/rebels/male_rebel_001_avg.ee", name: "Male Rebel 1"},
    {model_name: "editor/entities/jc_characters/rebels/male_rebel_002_avg.ee", name: "Male Rebel 2"},
    {model_name: "editor/entities/jc_characters/rebels/male_rebel_003_avg.ee", name: "Male Rebel 3"},
    {model_name: "editor/entities/jc_characters/rebels/male_rebel_004_avg.ee", name: "Male Rebel 4"},
    {model_name: "editor/entities/jc_characters/rebels/male_rebel_005_avg.ee", name: "Male Rebel 5"},
    {model_name: "editor/entities/jc_characters/rebels/male_rebel_006_avg.ee", name: "Male Rebel 6"},
    {model_name: "editor/entities/jc_characters/rebels/male_rebel_007_avg.ee", name: "Male Rebel 7"},
    {model_name: "editor/entities/jc_characters/rebels/male_rebel_008_avg.ee", name: "Male Rebel 8"},
    {model_name: "editor/entities/jc_characters/rebels/male_rebel_009_avg.ee", name: "Male Rebel 9"},
    {model_name: "editor/entities/jc_characters/rebels/male_rebel_010_avg.ee", name: "Male Rebel 10"},
    {model_name: "editor/entities/jc_characters/rebels/male_rebel_011_avg.ee", name: "Male Rebel 11"},
    {model_name: "editor/entities/jc_characters/rebels/rebel_grapple_immune_for_missions/female_rebel_004_grapple_melee_immune.ee", name: "Rebel Grapple Immune"}, // Maybe disable this
    {model_name: "editor/entities/jc_characters/rebels/rebel_paratrooper/spawned_rebel_paratrooper.ee", name: "Rebel Paratrooper"}
]